Add `Labels` tab to `Virtual Machines` resource page
harvester/dashboard pull request #1045
Opened 2024-06-05 14:06 UTC by votdev

### Summary
Allow the user to manage the labels of a Virtual Machine resource via UI. Right now it is only possible to manage instance labels that are synced from the VM to the VMI resource.

Fixes #https://github.com/harvester/harvester/issues/5974

### Screenshot/Video
![grafik](https://github.com/user-attachments/assets/43a63b15-6bdf-43f0-9a3b-911e07ea4868)

![grafik](https://github.com/harvester/harvester/assets/1897962/547eefbc-3370-4f5c-ba02-043c1154360c)

2024-09-26 13:17 UTC, torchiaf requested changes
LGTM, just a typo to remove.

2024-09-26 13:17 UTC, torchiaf commented on pkg/harvester/l10n/en-us.yaml
> +      description: Foo bar baz
```suggestion
      description: ''
```

2024-10-07 14:43 UTC, votdev commented on pkg/harvester/l10n/en-us.yaml
> +      description: Foo bar baz
Fixed

2024-10-10 08:09 UTC, torchiaf approved these changes
LGTM

2024-11-15 03:08 UTC, a110605 commented on pkg/harvester/l10n/en-us.yaml
> +      description: ""
Sorry, I can't find where to call the translation key, is this key needed?

```
harvester.virtualMachine.details.labels.description
```

2024-11-15 03:16 UTC, a110605 commented
I'm good to have `Labels` tab in virtual machine page. 👍 

But the https://github.com/harvester/harvester/issues/5974 is target to `v1.5.0` which will be released via `harvester-ui-extension` repo. 

We should have the same PR open for harvester-ui-extension and the shell KeyValue.vue and Labels.vue should have PR in [rancher/dashboard](https://github.com/rancher/dashboard).

Unless we want to backport this PR change to v1.4.x release, it's okay to merge in this repo master and backport to havester-release-v1.4 branch.  cc @torchiaf , @bk201

2025-01-21 11:00 UTC, torchiaf commented
I'd say, let's merge on harvester/dashboard master and make a porting to harvester extension afterwards.

2025-02-04 16:22 UTC, merged

2025-02-17 10:11 UTC, votdev commented
> I'm good to have `Labels` tab in virtual machine page.
> 
> But the [harvester/harvester#5974](https://github.com/harvester/harvester/issues/5974) targets to `v1.5.0` which will be released via [harvester-ui-extension](https://github.com/harvester/harvester-ui-extension) repo.
> 
> Since this PR changes `KeyValue.vue` and `Labels.vue` in shell, we need to open a PR merged to [rancher/dashboard](https://github.com/rancher/dashboard) and bump the [@ranchers/shell](https://www.npmjs.com/package/@rancher/shell) version, then update in harvester-ui-extension..
> 
> Unless we only want to target for v1.4.2. then we can merge in this `master` and backport to `havester-release-v1.4` branches.
> 
> cc @torchiaf , @bk201

The Rancher issue can be found at https://github.com/rancher/dashboard/issues/13397. The PR is at https://github.com/rancher/dashboard/pull/13398.