UI: allow all URL schemas for custom console URLs
harvester/dashboard pull request #1059
Opened 2024-06-27 12:44 UTC by m-ildefons

Allow all URL schemas for custom console URLs. This change removes a check that enforces the 'Console' button of a Harvester node to only redirect to URLs starting with `http://` or `https://`. Otherwise it will prepend `http://` to the configured URL. This breaks non-HTTP URL schemas like `vnc://` or `rtsx://`, which are sometimes used to launch custom VNC viewers instead of using the built-in one.

fixes: https://github.com/harvester/harvester/issues/6042

### Summary

#### PR Checklist
- Is this a multi-tenancy feature/bug? No.
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1? No.
- Are backend engineers aware of UI changes? No backend change associated with this fix.

Related Issue #
https://github.com/harvester/harvester/issues/6042

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2024-07-02 09:01 UTC, torchiaf commented
I think we should disable the console button if the consoleURL is invalid + we should validate the consoleURL field when editing the `hosts` from UI.
As mentioned in https://github.com/harvester/harvester/issues/6042#issuecomment-2195314002 the `^[a-z]+:\/\/`  regex can be used

2024-07-10 08:17 UTC, torchiaf requested changes
Just a small clean-up, otherwise LG

2024-07-10 08:17 UTC, torchiaf commented on pkg/harvester/models/harvester/node.js
> +    if ((!url) || (url.match(validator) === null)) {
This can be simplified as:
```suggestion
    if (!url?.match(validator)) {
```

2024-07-11 08:19 UTC, m-ildefons commented on pkg/harvester/models/harvester/node.js
> +    if ((!url) || (url.match(validator) === null)) {
Thanks for the suggestion, sounds good.

2024-07-11 09:48 UTC, torchiaf approved these changes
LGTM

2024-07-11 10:19 UTC, merged

2024-07-18 15:30 UTC, torchiaf commented
@mergify backport release-harvester-v1.4