HARVESTER: fixed create multiple vm instance (1504) & (1501)
harvester/dashboard pull request #161
Opened 2021-11-04 12:45 UTC by WuJun2016

# links
- https://github.com/harvester/harvester/issues/1504
- https://github.com/harvester/harvester/issues/1501
- https://github.com/harvester/harvester/issues/1512
- https://github.com/harvester/harvester/issues/1516

2021-11-05 11:11 UTC, n313893254 requested changes

2021-11-05 11:11 UTC, n313893254 commented on edit/harvesterhci.io.virtualmachinetemplateversion.vue
> +            this.errors = ['"Name" is required'];
Needs i18n

2021-11-05 12:02 UTC, WuJun2016 commented on edit/harvesterhci.io.virtualmachinetemplateversion.vue
> +            this.errors = ['"Name" is required'];
Done

2021-11-05 16:17 UTC, n313893254 requested changes

2021-11-05 16:17 UTC, n313893254 commented on edit/harvesterhci.io.virtualmachinetemplateversion.vue
> +            this.errors = [this.t('validation.required', { key: 'Name' })];
Name still not translate, It should be like this
```js
this.errors = [this.t('validation.required', { key: this.t('generic.name')})];
```

2021-11-08 05:37 UTC, n313893254 approved these changes

2021-11-08 05:37 UTC, merged