HARVESTER: fix vm unit display error
harvester/dashboard pull request #171
Opened 2021-11-17 09:28 UTC by WuJun2016

# links
- https://github.com/harvester/harvester/issues/1534
- https://github.com/harvester/harvester/issues/1429

Note: `memory.guest` is calculated by the backend

2021-11-17 14:30 UTC, weihanglo commented
It would be better if vm template version gets the same behaviour!
 https://github.com/harvester/harvester/pull/1554#issuecomment-971615050

2021-11-18 01:49 UTC, WuJun2016 commented
Thanks, the template has been synchronized and updated

2021-11-18 02:56 UTC, n313893254 requested changes

2021-11-18 02:56 UTC, n313893254 commented on detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineBasics.vue
> +      return `${ domain.cpu.cores } vCPU , ${ domain.resources.limits.memory } Memory`;
Is the "Memory" should be i10n?

2021-11-18 04:04 UTC, WuJun2016 commented
Done

2021-11-18 07:17 UTC, n313893254 approved these changes

2021-11-18 07:18 UTC, merged