fix 1709、1713、1724
harvester/dashboard pull request #212
Opened 2021-12-23 14:14 UTC by WuJun2016

# links
- https://github.com/harvester/harvester/issues/1724
- https://github.com/harvester/harvester/issues/1709
- https://github.com/harvester/harvester/issues/1713

2022-01-06 12:15 UTC, n313893254 requested changes

2022-01-06 12:15 UTC, n313893254 commented on list/harvesterhci.io.dashboard/index.vue
> +              Object.entries(statistics?.namespaces[resource.spoofed.filterNamespace[i]] || {}).forEach((entry) => {
```suggestion
              Object.entries(statistics?.namespaces[resource.spoofed.filterNamespace[i]?.states] || {}).forEach((entry) => {
```

![image](https://user-images.githubusercontent.com/18737885/148381533-917bcede-d480-4482-a34a-2eb6f7211be8.png)

2022-01-07 02:02 UTC, WuJun2016 commented on list/harvesterhci.io.dashboard/index.vue
> +              Object.entries(statistics?.namespaces[resource.spoofed.filterNamespace[i]] || {}).forEach((entry) => {
Done,  PTAL, thanks

2022-01-07 02:49 UTC, n313893254 approved these changes

2022-01-07 02:49 UTC, merged