added in selectors for automated login tests and settings tests
harvester/dashboard pull request #229
Opened 2022-01-20 02:00 UTC by noahgildersleeve

removed extra ID that wasn't used

2022-01-20 18:17 UTC, noahgildersleeve commented
So I see some commits in there that looked a little odd. I think it was based on trying to rebase from the upstream master branch to get everything in my fork. I'm not sure why it was showing up like that though.

2022-01-21 02:33 UTC, n313893254 commented
As every rebase is a force-push to the master branch. we need to cherry-pick the commits based on the new master branch.
Here is an example to rebase does not need to close the PR:

```bash
git branch -D master
git fetch origin
git checkout origin/master
git checkout -b master
git cherry-pick 4adbefd
git branch -D pom-selector-updates
git checkout -b pom-selector-updates
git push fork -f
```

**Addictional Context**
[.git/config]
```bash
[remote "origin"]
        url = git@github.com:harvester/dashboard.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[remote "fork"]
        url = git@github.com:noahgildersleeve/dashboard.git
        fetch = +refs/heads/*:refs/remotes/fork/*
```

2022-01-21 22:29 UTC, noahgildersleeve commented
I fixed it. Thanks for the help.

2022-01-22 06:18 UTC, WuJun2016 requested changes
@noahgildersleeve  Spelling error not fixed.

2022-01-24 02:17 UTC, noahgildersleeve commented on pages/auth/setup.vue
> +          <div id="submit" lass="text-center mt-20">
I updated it. Thanks.

2022-01-24 02:20 UTC, noahgildersleeve commented
Fixed.

2022-01-24 02:21 UTC, WuJun2016 approved these changes
LGTM

2022-01-24 02:25 UTC, merged