HARVESTER: prometheus configuration
harvester/dashboard pull request #247
Opened 2022-02-25 02:18 UTC by DaiYuzeng

## Linked Issues

- [https://github.com/harvester/harvester/issues/1531](https://github.com/harvester/harvester/issues/1531)

## Screenshots

#### setting list
![截屏2022-02-25 上午10 08 40](https://user-images.githubusercontent.com/15041915/155640969-836a3009-ac6f-496c-b8f0-38410950701c.png)

#### configuration
![截屏2022-02-25 上午10 08 50](https://user-images.githubusercontent.com/15041915/155641043-7d4a8c70-4d2b-4947-b7ab-ef3fe1326f8d.png)

## Test steps
1. Go to Setting Page
2. Click `Edit Config` on rancher-monitoring section
3. Edit configuration
4. Save

2022-02-28 03:41 UTC, guangbochen approved these changes
Both the design and typo is LGTM.

2022-03-01 02:46 UTC, DaiYuzeng commented on models/harvester/management.cattle.io.managedchart.js
> +    return spec ? JSON.stringify(spec) : '';
Done.

2022-03-01 08:52 UTC, WuJun2016 requested changes
Add description and show `modify`.

2022-03-01 09:33 UTC, DaiYuzeng commented
## Test steps
1. Go to Setting Page
2. Click `Edit Config` on harvester-monitoring section
3. Edit configuration
4. Succeed save
5. harvester-monitoring section will display correct JSON string
6. harvester-monitoring section on Setting Page will display modified status if you modified the configuration

2022-03-02 00:56 UTC, WuJun2016 approved these changes
LGTM

2022-03-02 01:02 UTC, merged

2022-03-03 09:33 UTC, w13915984028 commented
@guangbochen 

One doubt: the disk size seems to be limited to a dedicated partition of 50G now, does it make sense to change it here?
Not sure if user change it to a unavailable size, what will happen.

![image](https://user-images.githubusercontent.com/31133476/156536631-15117d07-d928-49fd-96ae-d27754b5961a.png)