Harvester: typology field is inputable if get nodes failed
harvester/dashboard pull request #391
Opened 2022-07-27 06:22 UTC by DaiYuzeng

### Summary

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/2567

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-07-28 07:55 UTC, n313893254 approved these changes
LGTM

2022-07-28 14:01 UTC, WuJun2016 requested changes

2022-07-28 14:01 UTC, WuJun2016 commented on shell/machine-config/harvester.vue
> +      }
I think this part should also be put inside` if (clusterId && isImportCluster)`，  The external cluster does not need to request the node api.

2022-07-28 14:01 UTC, WuJun2016 commented on shell/machine-config/harvester.vue
> +      }
other LGTM.

2022-07-29 08:12 UTC, WuJun2016 requested changes
Question:
1. If is a importCluster, the `Pods in these namespaces:` should be selectable。
2. Which cluster should be the source of namespace ?

2022-08-01 08:58 UTC, WuJun2016 approved these changes
LGTM

2022-08-01 09:05 UTC, WuJun2016 commented
@n313893254  Can you help to review it again?  thanks.

2022-08-02 03:49 UTC, merged