Harvester: Implement Alertmanager
harvester/dashboard pull request #411
Opened 2022-08-29 07:51 UTC by DaiYuzeng

### Summary

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/2643

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-09-13 21:59 UTC, mantis-toboggan-md requested changes
I think it would be better to disable the 'create' button when the banner saying configs can't be created is shown. As it is now, it's a little confusing: 
![Screen Shot 2022-09-13 at 2 57 12 PM](https://user-images.githubusercontent.com/42977925/190016895-91e31355-de3c-4113-a561-e33e87e621d7.png)

Aside from this and the translation comments, the PR looks/works good.

2022-09-13 21:59 UTC, mantis-toboggan-md commented on pkg/harvester/l10n/en-us.yaml
> +      one { AlertmanagerConfig }
Same as above, `Alertmanager Config` and `Alertmanager Configs`

2022-09-13 21:59 UTC, mantis-toboggan-md commented on pkg/harvester/l10n/en-us.yaml
> +      label: AlertmanagerConfigs
This should probably be `Alertmanager Configs`

2022-09-15 03:57 UTC, WuJun2016 requested changes
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/24985926/190310569-c5f4e566-eb53-42c2-838d-ae8e2d78ee61.png">

Delete `Cancel` button, other LGTM

2022-09-19 14:19 UTC, WuJun2016 commented
other LGTM，

The Disable `Create` button is not [working](https://github.com/harvester/dashboard/pull/411/files#diff-8b795e0d77fe25ef54f4c626b129005448c171d718f61f6dc920ee1a8290eedbR42) properly,   I think it's caused here https://github.com/rancher/dashboard/blob/c9a993f197973d9568af674742e338aa11cd996f/shell/store/type-map.js#L1547
 
I think we should override the value of `state.typeOptions[idx]` use `obj`,  

`Object.assign(obj, state.typeOptions[idx])  => Object.assign(state.typeOptions[idx], obj)`

@mantis-toboggan-md    Can you help confirm it ?  thanks

2022-09-19 14:30 UTC, WuJun2016 commented
> other LGTM，
> 
> The Disable `Create` button is not [working](https://github.com/harvester/dashboard/pull/411/files#diff-8b795e0d77fe25ef54f4c626b129005448c171d718f61f6dc920ee1a8290eedbR42) properly, I think it's caused here https://github.com/rancher/dashboard/blob/c9a993f197973d9568af674742e338aa11cd996f/shell/store/type-map.js#L1547
> 
> I think we should override the value of `state.typeOptions[idx]` use `obj`,
> 
> `Object.assign(obj, state.typeOptions[idx]) => Object.assign(state.typeOptions[idx], obj)`
> 
> @mantis-toboggan-md Can you help confirm it ? thanks

Test method: 
switch between disabled and enabled, the Create button on the alertmanagerconfig page should be correctly hidden or displayed

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/24985926/191041692-b6019462-c325-4264-9846-0c41f07ea169.png">

2022-09-20 02:44 UTC, merged