HARVESTER: add backup healthy check
harvester/dashboard pull request #413
Opened 2022-09-05 07:17 UTC by WuJun2016

### Summary
Fixes # 
- https://github.com/harvester/harvester/pull/2698

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-09-14 22:25 UTC, mantis-toboggan-md requested changes
PR seems to work well, I just have one minor request on the translation strings.

2022-09-14 22:25 UTC, mantis-toboggan-md commented on pkg/harvester/l10n/en-us.yaml
> +        successLabel: Test connection
```
waitingLabel: Testing connection...
successLabel: Connection tested
```

2022-09-15 01:46 UTC, WuJun2016 commented on pkg/harvester/l10n/en-us.yaml
> +        successLabel: Test connection
Done

2022-09-15 02:14 UTC, WuJun2016 commented
@mantis-toboggan-md  To give the QA more time to test, I want to merge the PR first.  thanks

2022-09-15 02:14 UTC, merged