HARVESTER: polish namespace
harvester/dashboard pull request #550
Opened 2022-12-15 08:15 UTC by WuJun2016

### Summary

#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [x] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    ~- [ ] Yes, the relevant PR is at:~
- Are backend engineers aware of UI changes?
    ~- [ ] Yes, the backend owner is:~

Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-02-14 14:16 UTC, n313893254 requested changes
Others LGTM

2023-02-14 14:16 UTC, n313893254 commented on pkg/harvester/store/harvester-store/getters.ts
> +          label: 'Not in a Project',
```suggestion
          label: rootGetters['i18n/t']('nav.ns.orphan'),
```

2023-02-15 02:25 UTC, WuJun2016 commented on pkg/harvester/store/harvester-store/getters.ts
> +          label: 'Not in a Project',
Done

2023-02-15 02:25 UTC, WuJun2016 commented on pkg/harvester/models/namespace.js
> +    return !!OBSCURE_NAMESPACE_PREFIX.some(prefix => this.metadata.name.startsWith(prefix));
Done

2023-02-15 02:26 UTC, WuJun2016 commented
Done, PTAL again, thanks

2023-02-15 03:05 UTC, n313893254 approved these changes
LGTM

2023-02-15 03:05 UTC, merged