HARVESTER: PCI device UI changes
harvester/dashboard pull request #595
Opened 2023-02-21 01:52 UTC by DaiYuzeng

### Summary

#### PR Checklist
- ~Is this a multi-tenancy feature/bug?~
    - ~[ ] Yes, the relevant RBAC changes are at:~
- ~Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?~
    - ~[ ] Yes, the relevant PR is at:~
- ~Are backend engineers aware of UI changes?~
    - ~[ ] Yes, the backend owner is:~

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/3146

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-02-22 04:52 UTC, n313893254 reviewed
@DaiYuzeng  Does the PCI dropdown need to filter by node selector?

![image](https://user-images.githubusercontent.com/18737885/220524923-19001ca1-a4f0-4c3a-bb5d-d65ed0d8afee.png)

![image](https://user-images.githubusercontent.com/18737885/220524952-d708706e-16dd-4187-92f3-edf209d09f8a.png)

2023-02-22 04:53 UTC, DaiYuzeng commented
Good question, I need to confirm that. Thanks! @n313893254

2023-02-23 10:25 UTC, n313893254 requested changes
1. PCI devices selector should be disabled on the detail config page
![image](https://user-images.githubusercontent.com/18737885/220868861-a5657db7-b1f1-4c0b-9f02-cb828f508170.png)

2023-02-23 10:25 UTC, n313893254 commented on pkg/harvester/l10n/en-us.yaml
> +    matrixHostName: Hostname
Should be `Host Name` ?

2023-02-23 10:25 UTC, n313893254 commented on pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/CompatibilityMatrix.vue
> +      const name = deviceCRD.status?.metadata?.name;
```suggestion
      const name = deviceCRD.metadata?.name;
```

2023-02-23 10:25 UTC, n313893254 commented on pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/CompatibilityMatrix.vue
> +      const name = deviceCRD.status?.metadata?.name;
```suggestion
      const name = deviceCRD.metadata?.name;
```

2023-02-23 10:25 UTC, n313893254 commented on pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/CompatibilityMatrix.vue
> +    vmsUsingDevice(deviceCRD) {
Seems it is an unused method. Could we remove it?

2023-02-24 03:50 UTC, n313893254 approved these changes
LGTM

2023-02-24 03:50 UTC, merged