Allow adding `Expected Checksum` when creating a new image
harvester/dashboard pull request #954
Opened 2024-02-14 16:27 UTC by votdev

- Add validator at model level (legacy) because the whole page is not using form field validators.

### Summary

#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

Fixes https://github.com/harvester/harvester/issues/5141

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2024-02-16 08:25 UTC, FrankYang0529 approved these changes
LGTM. The result works as expected. Thanks for the improvement

2024-02-16 08:26 UTC, FrankYang0529 approved these changes

2024-02-22 11:26 UTC, torchiaf commented
LG overall, I just have a question about Checksum format.
Does Harvester alse support SHA256 format ? If so, the validator should take it in consideration.

2024-02-22 11:27 UTC, torchiaf requested changes
LG overall, I just have a question about Checksum format.
Does Harvester alse support SHA256 format ? If so, the validator should take it in consideration @bk201 .

2024-02-23 07:49 UTC, bk201 commented
yeah supposed to be sha512 sum.

2024-02-23 11:47 UTC, merged

2024-02-23 13:33 UTC, votdev commented
# Test case 1

1. Go to the `Images` page and press `Create`.
2. Check the `URL` radio box
3. Add the following URL: `https://fastly-cdn.system-rescue.org/releases/11.00/systemrescue-11.00-amd64.iso`
4. Add the `Checksum`: `10a3145a5101c00977091e7c946086edcc5e4acf8dfb57b1e912fdf27c23899cedc12cf14ef503a18a1018f917066149957d7460f3c080e2891af64cac05bc35`
5. Press `Create`
6. Run the following commands. The output should look like this:
```
$ k get virtualmachineimages 
NAME          DISPLAY-NAME                   SIZE        AGE
image-pk6wl   systemrescue-11.00-amd64.iso   894435328   8s
```
7. Run
```
$ k get virtualmachineimages image-pk6wl -o jsonpath="{.spec}" | jq
{
  "checksum": "10a3145a5101c00977091e7c946086edcc5e4acf8dfb57b1e912fdf27c23899cedc12cf14ef503a18a1018f917066149957d7460f3c080e2891af64cac05bc35",
  "displayName": "systemrescue-11.00-amd64.iso",
  "pvcName": "",
  "pvcNamespace": "",
  "retry": 3,
  "sourceType": "download",
  "storageClassParameters": {
    "migratable": "true",
    "numberOfReplicas": "3",
    "staleReplicaTimeout": "30"
  },
  "url": "https://fastly-cdn.system-rescue.org/releases/11.00/systemrescue-11.00-amd64.iso"
}
```
The checksum property must be the same as the entered one.
8. When the download is done, then there should be no warning message in the UI.

# Test case 2

1. Go to the `Images` page and press `Create`.
2. Check the `URL` radio box
3. Add the following URL: `https://fastly-cdn.system-rescue.org/releases/11.00/systemrescue-11.00-amd64.iso`
4. Add the incorrect `Checksum`: `aaaaa45a5101c00977091e7c946086edcc5e4acf8dfb57b1e912fdf27c23899cedc12cf14ef503a18a1018f917066149957d7460f3c080e2891af64cac05bc35`
5. Press `Create`
6. After 3 download attempts the error message 
```
Failed to process sync file: the expected checksum  aaaaa45a5101c00977091e7c946086edcc5e4acf8dfb57b1e912fdf27c23899cedc12cf14ef503a18a1018f917066149957d7460f3c080e2891af64cac05bc35  doesn't match the file actual checksum  10a3145a5101c00977091e7c946086edcc5e4acf8dfb57b1e912fdf27c23899cedc12cf14ef503a18a1018f917066149957d7460f3c080e2891af64cac05bc35
```
should be shown in the `Images` page.
![grafik](https://github.com/harvester/dashboard/assets/1897962/26abdf5e-7b97-481f-b0aa-16bda1cee155)

# Test case 3
1. Go to the `Images` page and press `Create`.
2. Check the `URL` radio box
3. Add the following URL: `https://fastly-cdn.system-rescue.org/releases/11.00/systemrescue-11.00-amd64.iso`
4. Add the following `Checksum`: `c5e4acf8dfb57b1e912fdf27`
5. Press `Create`
6. The following error should appear.
![grafik](https://github.com/harvester/dashboard/assets/1897962/dcd5db51-d19b-4ac0-862d-f3ce5e57bf03)